name: "Build and checks"
on:
  pull_request:
    branches:
      - master
      - dev
jobs:
  check_hugo_site:
    name: Check Hugo site
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: CodeIT
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          path: 'CodeIT'
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: Build static pages
        run: hugo --source=exampleSite -v --gc
      - name: Check HTML
        uses: chabad360/htmlproofer@master
        with:
          directory: "CodeIT/exampleSite/public"
          arguments: --check-html --allow-hash-href --empty-alt-ignore --disable-external
